version: 1.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Bundle Installation check
          bundle install
          command: |
            echo 'Bundle Installation Check Done!'
      
      - run:
          name: The First Step
          bundle install
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
